package runtime

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/tiny-oc/toc/internal/agent"
)

func claudeInstructionPathMapper(rel string) string {
	if rel == "CLAUDE.md" {
		return "agent.md"
	}
	return rel
}

func buildClaudeHookSettings(syncScriptPath string, onEnd string, permScriptPath string) ([]byte, error) {
	hooks := map[string]interface{}{}

	if syncScriptPath != "" {
		hooks["PostToolUse"] = []map[string]interface{}{
			{
				"matcher": "Edit|Write|MultiEdit",
				"hooks": []map[string]interface{}{
					{
						"type":    "command",
						"command": syncScriptPath,
					},
				},
			},
		}
	}

	if onEnd != "" {
		hooks["SessionEnd"] = []map[string]interface{}{
			{
				"hooks": []map[string]interface{}{
					{
						"type":   "agent",
						"prompt": onEnd,
					},
				},
			},
		}
	}

	if permScriptPath != "" {
		hooks["PreToolUse"] = []map[string]interface{}{
			{
				"hooks": []map[string]interface{}{
					{
						"type":    "command",
						"command": permScriptPath,
					},
				},
			},
		}
	}

	settings := map[string]interface{}{
		"hooks": hooks,
	}
	return json.MarshalIndent(settings, "", "  ")
}

func buildClaudeSyncHookScript(sessionDir, agentDir string, patterns []string) string {
	var patternArgs []string
	for _, p := range patterns {
		patternArgs = append(patternArgs, fmt.Sprintf("%q", p))
	}

	return fmt.Sprintf(`#!/usr/bin/env bash
# Auto-generated by toc — syncs context files back to agent template.
# This script is called by Claude Code's PostToolUse hook.

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | grep -o '"file_path"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*"file_path"[[:space:]]*:[[:space:]]*"//' | sed 's/"$//')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

if [[ "$FILE_PATH" != /* ]]; then
  FILE_PATH="%s/$FILE_PATH"
fi

if [ ! -f "$FILE_PATH" ]; then
  exit 0
fi

REL_PATH="${FILE_PATH#%s/}"

if [ "$REL_PATH" = "$FILE_PATH" ]; then
  exit 0
fi

DST_REL="$REL_PATH"
if [ "$REL_PATH" = "CLAUDE.md" ]; then
  DST_REL="agent.md"
fi

AGENT_DIR="%s"
PATTERNS=(%s)

for PATTERN in "${PATTERNS[@]}"; do
  DIR_PATTERN="${PATTERN%%/}"
  if [ "$DIR_PATTERN" != "$PATTERN" ] || [ -d "%s/$DIR_PATTERN" ] 2>/dev/null; then
    if [[ "$DST_REL" == "$DIR_PATTERN"/* ]] || [ "$DST_REL" = "$DIR_PATTERN" ]; then
      mkdir -p "$(dirname "$AGENT_DIR/$DST_REL")"
      cp "$FILE_PATH" "$AGENT_DIR/$DST_REL"
      exit 0
    fi
  fi

  case "$DST_REL" in
    $PATTERN)
      mkdir -p "$(dirname "$AGENT_DIR/$DST_REL")"
      cp "$FILE_PATH" "$AGENT_DIR/$DST_REL"
      exit 0
      ;;
  esac

  BASENAME=$(basename "$DST_REL")
  if [[ "$PATTERN" != */* ]]; then
    case "$BASENAME" in
      $PATTERN)
        mkdir -p "$(dirname "$AGENT_DIR/$DST_REL")"
        cp "$FILE_PATH" "$AGENT_DIR/$DST_REL"
        exit 0
        ;;
    esac
  fi
done
`, sessionDir, sessionDir, agentDir, strings.Join(patternArgs, " "), sessionDir)
}

func buildClaudePermissionHookScript(perms agent.Permissions, agentName string) string {
	readDecision := string(perms.Filesystem.Read)
	writeDecision := string(perms.Filesystem.Write)
	execDecision := string(perms.Filesystem.Execute)

	var integrationCases strings.Builder

	return fmt.Sprintf(`#!/usr/bin/env bash
# Auto-generated by toc — enforces agent permission config.
# This script is called by Claude Code's PreToolUse hook.
# Agent: %s

set -euo pipefail

INPUT=$(cat)
TOOL_NAME=$(echo "$INPUT" | grep -o '"tool_name"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*"tool_name"[[:space:]]*:[[:space:]]*"//' | sed 's/"$//')

if [ -z "$TOOL_NAME" ]; then
  exit 0
fi

decide_read() {
  local LEVEL="%s"
  case "$LEVEL" in
    off)
      echo '{"decision":"block","reason":"Agent \"%s\" does not have filesystem read permission"}'
      ;;
    ask)
      ;;
    *)
      echo '{"decision":"allow"}'
      ;;
  esac
}

decide_write() {
  local LEVEL="%s"
  case "$LEVEL" in
    off)
      echo '{"decision":"block","reason":"Agent \"%s\" does not have filesystem write permission"}'
      ;;
    ask)
      ;;
    *)
      echo '{"decision":"allow"}'
      ;;
  esac
}

decide_exec() {
  local LEVEL="%s"
  case "$LEVEL" in
    off)
      echo '{"decision":"block","reason":"Agent \"%s\" does not have shell execute permission"}'
      ;;
    ask)
      ;;
    *)
      echo '{"decision":"allow"}'
      ;;
  esac
}

case "$TOOL_NAME" in
  Read|Glob|Grep)
    decide_read
    ;;
  Edit|Write|MultiEdit|NotebookEdit)
    decide_write
    ;;
  Bash)
    decide_exec
    ;;
%s  *)
    echo '{"decision":"allow"}'
    ;;
esac
`, agentName,
		readDecision, agentName,
		writeDecision, agentName,
		execDecision, agentName,
		integrationCases.String())
}
